// <auto-generated />
using SMBSpider;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Net;
using System.IO;

namespace SMBSpiderTest
{
    
    
    /// <summary>
    ///Dies ist eine Testklasse für "SmbScannerTest" und soll
    ///alle SmbScannerTest Komponententests enthalten.
    ///</summary>
    [TestClass()]
    public class SmbScannerTest
    {

        private TestContext testContextInstance;

        /// <summary>
        ///Ruft den Testkontext auf, der Informationen
        ///über und Funktionalität für den aktuellen Testlauf bietet, oder legt diesen fest.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }

        #region Zusätzliche Testattribute
        // 
        //Sie können beim Verfassen Ihrer Tests die folgenden zusätzlichen Attribute verwenden:
        //
        //Mit ClassInitialize führen Sie Code aus, bevor Sie den ersten Test in der Klasse ausführen.
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Mit ClassCleanup führen Sie Code aus, nachdem alle Tests in einer Klasse ausgeführt wurden.
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Mit TestInitialize können Sie vor jedem einzelnen Test Code ausführen.
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Mit TestCleanup können Sie nach jedem einzelnen Test Code ausführen.
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///Ein Test für "Scan"
        ///</summary>
        [TestMethod()]
        public void ScanTest()
        {
            IHandleResult resultHandler = new MockUpResultHandler();
            IPAddress[] addresses = new IPAddress[]{ IPAddress.Parse("141.52.34.16")};
            SmbScanner target = new SmbScanner(resultHandler, addresses);
            target.Scan();
            string[] results = ((MockUpResultHandler)resultHandler).GetResults();

            Assert.IsTrue(results.Length != 0);
        }
    }
}
